# permissions for end users to edit ndbservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ndbserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ndb-operator
    app.kubernetes.io/part-of: ndb-operator
    app.kubernetes.io/managed-by: kustomize
  name: ndbserver-editor-role
rules:
- apiGroups:
  - ndb.nutanix.com
  resources:
  - ndbservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ndb.nutanix.com
  resources:
  - ndbservers/status
  verbs:
  - get
