---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ndb.nutanix.com
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ndb.nutanix.com
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - ndb.nutanix.com
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ndb.nutanix.com
  resources:
  - dataprotections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ndb.nutanix.com
  resources:
  - dataprotections/finalizers
  verbs:
  - update
- apiGroups:
  - ndb.nutanix.com
  resources:
  - dataprotections/status
  verbs:
  - get
  - patch
  - update
