# permissions for end users to edit snapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: snapshot-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ndb-operator
    app.kubernetes.io/part-of: ndb-operator
    app.kubernetes.io/managed-by: kustomize
  name: snapshot-editor-role
rules:
- apiGroups:
  - ndb.nutanix.com
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ndb.nutanix.com
  resources:
  - snapshots/status
  verbs:
  - get
