apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
    name: db
spec:
    ndb:
        clusterId: 'f703bdb6-b9c1-4dd8-a0fd-236ccd4af306'
        credentialSecret: ntnx2-ndb-secret
        server: https://erap2t9rkwz1x-era.nutanixtestdrive.com/era/v0.9
        skipCertificateVerification: true
    databaseInstance:
        databaseInstanceName: 'test_mysql2'
        databaseNames:
            - database_one_mysql
            - database_two_mysql
            - database_three_mysql
        credentialSecret: ntnx2-db-secret
        size: 10
        timezone: 'UTC'
        type: mysql
