apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
    name: db2
spec:
    ndb:
        clusterId: 'fd92c1bd-685e-42b3-9113-4057a23d2fc6'
        credentialSecret: ntnx2-ndb-secret
        server: https://eravoaqxn7x49-era.nutanixtestdrive.com/era/v0.9
        skipCertificateVerification: true
    databaseInstance:
        databaseInstanceName: 'test2'
        databaseNames:
            - database_one
            - database_two
            - database_three
        credentialSecret: ntnx2-db-secret
        size: 10
        timezone: 'UTC'
        type: postgres
