apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
    name: db
spec:
    ndb:
        clusterId: '780e11d1-a389-4a04-86ec-eb1a0ac7e162'
        credentialSecret: ntnx2-ndb-secret
        server: https://eravoiwrziyev-era.nutanixtestdrive.com/era/v0.9
        skipCertificateVerification: true
    databaseInstance:
        databaseInstanceName: 'test_mysql2'
        databaseNames:
            - database_one_mysql
            - database_two_mysql
            - database_three_mysql
        credentialSecret: ntnx2-db-secret
        size: 10
        timezone: 'UTC'
        type: mysql
