apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
    name: db
spec:
    ndb:
        clusterId: '6886c490-0432-4aa8-8d91-c701bdefabbc'
        credentialSecret: ntnx2-ndb-secret
        server: https://erawgibl2jvw4-era.nutanixtestdrive.com/era/v0.9
        skipCertificateVerification: true
    databaseInstance:
        databaseInstanceName: 'test_postgres'
        databaseNames:
            - database_one
            - database_two
            - database_three
        credentialSecret: ntnx2-db-secret
        size: 10
        timezone: 'UTC'
        type: postgres
