apiVersion: v1
kind: Secret
metadata:
  name: ndb-secret-name
type: Opaque
stringData:
  username: testNdbServer
  password: testNdbPassword
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    CA CERTIFICATE (ca_certificate is optional)
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  name: db-instance-secret-name
type: Opaque
stringData:
  password: test123
  ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5c1Kfw2w6gTcv/GYH6tr+RtVS2dITV7hirQrlrUFTXbvOS4lRgpRwxY2BjVh7TjgKQ6ZiS+09rIABCIDeV1GP6n2651XYJ161J9qfGSjZphIh48qiQGdkDlPa2fh1aQkUxdjIzh42/hDFrlZWXKBS0V2jiCiqa8R8kgEGLiYsbJb/Pa+4G39/F85kg3JdNeeSFl7w9Cxrfn225/2ISQeaD6S+gOrvvfrcDLDU+q3jxbkB3vU4mqt+4tC4G24tjPZr93vdFkroXr3HpjmAHSABWL2tkKc3encAaIEH0+OI2HKeXIYdOYQsprv8/6/0OyNwEmTdSN4qn9Q8PPtRnqbj 
