/*
Copyright 2022-2026 Nutanix, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
GENERATED by operator-sdk
Changes added
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DatabaseSpec defines the desired state of Database
type DatabaseSpec struct {
	// +kubebuilder:validation:Required
	NDBRef string `json:"ndbRef"`
	// +optional
	// DefaultsConfigMapRef references a ConfigMap containing default values
	// for database configuration. Values explicitly set in this spec take
	// precedence over ConfigMap defaults. The ConfigMap should be in the same
	// namespace as the Database resource.
	DefaultsConfigMapRef string `json:"defaultsConfigMapRef,omitempty"`
	// +optional
	IsClone bool `json:"isClone"`
	// +optional
	Instance *Instance `json:"databaseInstance"`
	// +optional
	Clone *Clone `json:"clone"`
}

// DatabaseStatus defines the observed state of Database
type DatabaseStatus struct {
	IPAddress                 string `json:"ipAddress"`
	Id                        string `json:"id"`
	Status                    string `json:"status"`
	DatabaseServerId          string `json:"dbServerId"`
	Type                      string `json:"type"`
	CreationOperationId       string `json:"creationOperationId"`
	DeregistrationOperationId string `json:"deregistrationOperationId"`
	// DBServerDeletionOperationIds holds the NDB operation ID returned by the DPC (DBServerCluster) deletion.
	// Populated when HA deletion starts; polled until the operation completes before the finalizer is removed.
	DBServerDeletionOperationIds []string `json:"dbServerDeletionOperationIds,omitempty"`
}

// Database is the Schema for the databases API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName={"db","dbs"}
// +kubebuilder:printcolumn:name="IP Address",type=string,JSONPath=`.status.ipAddress`
// +kubebuilder:printcolumn:name="Status",type=string,JSONPath=`.status.status`
// +kubebuilder:printcolumn:name="Type",type=string,JSONPath=`.status.type`
type Database struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DatabaseSpec   `json:"spec,omitempty"`
	Status DatabaseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// DatabaseList contains a list of Database
type DatabaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Database `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Database{}, &DatabaseList{})
}

// These are required to have a deep copy, object interface implementation
// These are the structs for the Spec and Status

// InstanceHANode describes the placement and role of a single VM in an HA cluster.
type InstanceHANode struct {
	// Name of the VM to be created
	// +kubebuilder:validation:Required
	VmName string `json:"vmName"`
	// Type of this node:
	// database, haproxy (Postgres HA), mysqlrouter (MySQL HA), or arbiter (MongoDB HA)
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=haproxy;database;mysqlrouter;arbiter
	NodeType string `json:"nodeType"`
	// Role of this node (database nodes only):
	// Primary or Secondary
	// +optional
	Role string `json:"role,omitempty"`
	// Id of the PE cluster this node should be placed on.
	// Either clusterId or clusterName must be provided.
	// +optional
	ClusterId string `json:"clusterId,omitempty"`
	// Name of the PE cluster this node should be placed on.
	// Either clusterId or clusterName must be provided.
	// +optional
	ClusterName string `json:"clusterName,omitempty"`
	// Failover mode for database nodes (default "Automatic")
	// +optional
	FailoverMode string `json:"failoverMode,omitempty"`
}

// InstanceHAConfig holds the HA provisioning configuration for a database instance.
// Generic fields (ClusterName, EnableSynchronousMode, Nodes) apply to all HA engines.
// Engine-specific settings are nested under the corresponding engine field (e.g. Postgres, MySQL).
// Exactly one engine field must be set, matching the instance.type.
type InstanceHAConfig struct {
	// Display name for the NDB HA cluster
	// +kubebuilder:validation:Required
	ClusterName string `json:"clusterName"`
	// Enable synchronous replication mode
	// +optional
	EnableSynchronousMode bool `json:"enableSynchronousMode,omitempty"`
	// Node placement and role definitions for all VMs in the HA cluster
	// +kubebuilder:validation:Required
	Nodes []InstanceHANode `json:"nodes"`
	// Postgres contains Patroni and HAProxy settings specific to Postgres HA.
	// Required when the database type is "postgres".
	// +optional
	Postgres *PostgresHAConfig `json:"postgres,omitempty"`
	// MySQL contains InnoDB Cluster and MySQL Router settings specific to MySQL HA.
	// Required when the database type is "mysql".
	// +optional
	MySQL *MySQLHAConfig `json:"mysql,omitempty"`
	// MongoDB contains Replica Set settings specific to MongoDB HA.
	// Required when the database type is "mongodb".
	// +optional
	MongoDB *MongoHAConfig `json:"mongodb,omitempty"`
}

// MySQLHAConfig holds InnoDB Cluster and MySQL Router settings specific to a MySQL HA instance.
type MySQLHAConfig struct {
	// Name used by MySQL InnoDB Cluster for internal cluster coordination
	// +kubebuilder:validation:Required
	InnoDBClusterName string `json:"innoDBClusterName"`
	// DeployMySQLRouter controls whether MySQL Router VMs are provisioned for load balancing.
	// When true, Router VMs must be included in nodes[] with nodeType "mysqlrouter",
	// When false, applications connect directly to the Master VM on port 3306.
	// +optional
	DeployMySQLRouter bool `json:"deployMySQLRouter,omitempty"`
	// RouterRWPort is the MySQL Router read-write port. Defaults to 6446.
	// Only meaningful when DeployMySQLRouter is true.
	// +optional
	// +kubebuilder:default=6446
	RouterRWPort int32 `json:"routerRWPort,omitempty"`
	// RouterROPort is the MySQL Router read-only port. Defaults to 6447.
	// Only meaningful when DeployMySQLRouter is true.
	// +optional
	// +kubebuilder:default=6447
	RouterROPort int32 `json:"routerROPort,omitempty"`
	// MySQLClusterUsername is the admin user for InnoDB Cluster management. Defaults to "mysqladmin".
	// +optional
	MySQLClusterUsername string `json:"mysqlClusterUsername,omitempty"`
	// ReplicationUser is the user for group replication. Defaults to "repl".
	// +optional
	ReplicationUser string `json:"replicationUser,omitempty"`
}

// PostgresHAConfig holds Patroni and HAProxy settings specific to a Postgres HA instance.
type PostgresHAConfig struct {
	// Name used by Patroni for DCS cluster coordination
	// +kubebuilder:validation:Required
	PatroniClusterName string `json:"patroniClusterName"`
	// HAProxy write (primary) port. Defaults to 5000.
	// +optional
	// +kubebuilder:default=5000
	WritePort int32 `json:"writePort,omitempty"`
	// HAProxy read (replica) port. Defaults to 5001.
	// +optional
	// +kubebuilder:default=5001
	ReadPort int32 `json:"readPort,omitempty"`
	// ProvisionVirtualIP controls whether NDB provisions a Virtual IP for the HAProxy layer.
	// Set to true only when all HAProxy VMs are on the same Nutanix cluster (non-stretched VLAN).
	// Defaults to false; use false when HAProxy nodes span multiple PE clusters.
	// +optional
	ProvisionVirtualIP bool `json:"provisionVirtualIP,omitempty"`
}

// MongoHAConfig holds Replica Set settings specific to a MongoDB HA instance.
type MongoHAConfig struct {
	// ReplicaSetName is the MongoDB Replica Set name, mapped to the "cluster_name" NDB action argument.
	// +kubebuilder:validation:Required
	ReplicaSetName string `json:"replicaSetName"`
	// ReplicaSetDescription is an optional human-readable description shown in the NDB UI.
	// +optional
	ReplicaSetDescription string `json:"replicaSetDescription,omitempty"`
	// DeployArbiter controls whether an Arbiter VM is provisioned.
	// When true, exactly one node with nodeType "arbiter" must be present in nodes[].
	// When false (default), no arbiter nodes may be present — all nodes are data-bearing.
	// +optional
	DeployArbiter bool `json:"deployArbiter,omitempty"`
	// ArbiterComputeProfileId optionally assigns a smaller compute profile to the Arbiter VM.
	// Falls back to the instance-level compute profile if unset.
	// Only meaningful when DeployArbiter is true.
	// +optional
	ArbiterComputeProfileId string `json:"arbiterComputeProfileId,omitempty"`
	// ListenerPort is the MongoDB listener port. Defaults to 27017.
	// +optional
	// +kubebuilder:default=27017
	ListenerPort int32 `json:"listenerPort,omitempty"`
}

// Database instance specific details
type Instance struct {
	// Name of the database instance
	Name string `json:"name"`
	// +optional
	// Description of the database instance
	Description string `json:"description"`
	// Id of the cluster to provision the database on
	// Either clusterId or clusterName must be provided
	// +optional
	ClusterId string `json:"clusterId,omitempty"`
	// Name of the cluster to provision the database on
	// Either clusterId or clusterName must be provided
	// +optional
	ClusterName string `json:"clusterName,omitempty"`
	// +optional
	Profiles *Profiles `json:"profiles"`
	// Name of the secret holding the credentials for the database instance (password and ssh key)
	CredentialSecret string `json:"credentialSecret"`
	// +optional
	// default UTC
	TimeZone string `json:"timezone"`
	// +optional
	// Name(s) of the database(s) to be provisioned inside the database instance
	// default [ "database_one", "database_two", "database_three" ]
	DatabaseNames []string `json:"databaseNames"`
	// Size of the database instance, minimum 10 (GBs)
	Size int    `json:"size"`
	Type string `json:"type"`
	// +optional
	// Information related to time machine that is to be associated with this database
	TMInfo *DBTimeMachineInfo `json:"timeMachine"`
	// +optional
	// Additional database engine specific arguments
	AdditionalArguments map[string]string `json:"additionalArguments"`
	// +optional
	// HA configuration for Postgres HA instances (multi-cluster topology).
	// When set, provisions a clustered Postgres instance with HAProxy and Patroni.
	HAConfig *InstanceHAConfig `json:"haConfig,omitempty"`
}

type Clone struct {
	// Name of the clone instance
	Name string `json:"name"`
	// Description of the clone instance
	// +optional
	Description string `json:"description"`
	// Type of parent clone
	Type string `json:"type"`
	// Id of the cluster to clone the database on
	// Either clusterId or clusterName must be provided
	// +optional
	ClusterId string `json:"clusterId,omitempty"`
	// Name of the cluster to clone the database on
	// Either clusterId or clusterName must be provided
	// +optional
	ClusterName string `json:"clusterName,omitempty"`
	// +optional
	Profiles *Profiles `json:"profiles"`
	// Name of the secret holding the credentials for the database instance (password and ssh key)
	CredentialSecret string `json:"credentialSecret"`
	// +optional
	// default UTC
	TimeZone string `json:"timezone"`
	// Id of the source database on NDB to clone from
	// Either sourceDatabaseId or sourceDatabaseName must be provided
	// +optional
	SourceDatabaseId string `json:"sourceDatabaseId,omitempty"`
	// Name of the source database on NDB to clone from
	// Either sourceDatabaseId or sourceDatabaseName must be provided
	// +optional
	SourceDatabaseName string `json:"sourceDatabaseName,omitempty"`
	// Id of the snapshot to create a clone from
	// Either snapshotId or snapshotName must be provided
	// +optional
	SnapshotId string `json:"snapshotId,omitempty"`
	// Name of the snapshot to create a clone from
	// Either snapshotId or snapshotName must be provided
	// +optional
	SnapshotName string `json:"snapshotName,omitempty"`
	// +optional
	// Additional database engine specific arguments
	AdditionalArguments map[string]string `json:"additionalArguments"`
}

// Time Machine details
type DBTimeMachineInfo struct {
	// +optional
	Name string `json:"name"`
	// +optional
	Description string `json:"description"`
	// +optional
	// Name of the SLA to be used, default NONE
	SLAName string `json:"sla"`
	// +optional
	// Daily snapshot time in HH:MM:SS (24 hour format)
	DailySnapshotTime string `json:"dailySnapshotTime"`
	// +optional
	// Number of snapshots per day
	SnapshotsPerDay int `json:"snapshotsPerDay"`
	// +optional
	// Log catch up frequency in minutes
	LogCatchUpFrequency int `json:"logCatchUpFrequency"`
	// +optional
	// Day of the week for weekly snapshot
	WeeklySnapshotDay string `json:"weeklySnapshotDay"`
	// +optional
	// Day of the month for monthly snapshot
	MonthlySnapshotDay int `json:"monthlySnapshotDay"`
	// +optional
	// Start month for the quarterly snapshot
	// Jan => Jan, Apr, Jul, Oct.
	// Feb => Feb, May, Aug, Nov.
	// Mar => Mar, Jun, Sep, Dec.
	QuarterlySnapshotMonth string `json:"quarterlySnapshotMonth"`
}

type Profiles struct {
	// +optional
	Software Profile `json:"software"`
	// +optional
	Compute Profile `json:"compute"`
	// +optional
	Network Profile `json:"network"`
	// +optional
	DbParam Profile `json:"dbParam"`
	// +optional
	DbParamInstance Profile `json:"dbParamInstance"`
}

type Profile struct {
	// +optional
	Id string `json:"id"`
	// +optional
	Name string `json:"name"`
}
